version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: always

volumes:
  mongodb-data:
